name: Python and Terraform CI

on:
  push:
    branches:
      - main
  workflow_dispatch: # for manual triggering - to be removed later?

jobs:
  run-tests:
  
    name: run-tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        
      - name: Set Up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install Requirements/Dependencies
        run: 
          make requirements

      - name: Install Dev Requirements # Installs bandit, safety, coverage, flake8
        run: 
          make dev-setup 
          
      - name: Run Checks # Runs security, runs unit tests, checks coverage 
        run:
          make run-checks

      - name: Lint with Flake8
        run:
          make run-linter
        continue-on-error: true

  # Terraform Job
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: python  # Ensures that Python tests run first

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.1.0'

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_some_variable: ${{ secrets.TF_VAR_some_variable }}  # Example of environment variable usage
